name = "DataStructure101"
uuid = "0056bbaa-36c9-436f-bac2-baeddaff1525"
authors = ["JingYu Ning <foldfelis@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
